#inherit_from: .rubocop_todo.yml

# Offense count: 88
# Cop supports --auto-correct.
# Configuration parameters: AutoCorrect, AllowHeredoc, AllowURI, URISchemes, IgnoreCopDirectives, IgnoredPatterns.
# URISchemes: http, https
Layout/LineLength:
  Max: 140

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/HashAlignment:
  EnforcedHashRocketStyle: table
